### ISSUE TITLE
有关极验文字点选

### ISSUE THREAD

**Issue by zyhxa** [zscorpio/geetest#1]
我想请问一下文字点选中的参数userresponse的生成逻辑是什么呢？

**Comment by zscorpio** [comment]
可以看一下博客内容, 因为不想写双份readme, https://zscorpio.one/posts/geetest%E6%9E%81%E9%AA%8C%E7%82%B9%E9%80%89%E9%AA%8C%E8%AF%81%E7%A0%81%E4%BD%8D%E7%BD%AE%E8%AF%86%E5%88%AB/

**Comment by zyhxa** [comment]
好的谢谢您了

**Comment by zscorpio** [comment]
一共是3个数据

target: 识别出来待点击区域的文本.
source: 识别区域的文本以及坐标
coords: 最终实际文本顺序的中心相对坐标.

**Comment by zyhxa** [comment]
好的，明白了，谢谢
